### ISSUE TITLE
Number entry, tolerance and precision

### ISSUE THREAD

**Issue by BillFoster** [numbas/editor#176] opened 2013-10-17 12:06 UTC
If you set minimum and maximum accepted values to be the same in the marking section of a Number entry type question, then any Precision restriction is ignored (apart from when the number and its restriction are the same) - and any entry is marked as incorrect.  In order to make it work you have to set the min and max values to include the answer to the required precision. Better and more intuitive would be one of the following options, both of which separate setting tolerances and precision:
1. Have two modes of entry
   a) Set precision - this would have one field to enter the number and other fields for Precision setting as now
   b) Set tolerance as now with two fields- but no Precision setting. 
2. As now but allow Precision to be set if min=max . If min not equal to max then Precision ignored.

The first is  cleaner as it clearly distinguishes between tolerance and precision.

**Comment by christianp** [comment] 2017-09-27 14:41
This is a duplicate of numbas/Numbas#296

**Closed by christianp** 2017-09-27 14:41 UTC
Labels: wishlist
