### ISSUE TITLE
Error message on running questions after using search (V2 editor)

### ISSUE THREAD

**Issue by BillFoster** [numbas/editor#302] opened 2016-06-03 10:57 UTC
On running a  question from the search results after using the the top left search field to select questions I sometimes get the error message:

OSError at /question/13110/bill-s-copy-of-adding-and-subtracting-fractions/preview/
[Errno 12] Cannot allocate memory
Request Method:	GET
Request URL:	https://numbas.mathcentre.ac.uk/question/13110/bill-s-copy-of-adding-and-subtracting-fractions/preview/
Django Version:	1.8.13
Exception Type:	OSError
Exception Value:	
[Errno 12] Cannot allocate memory

etc....

But on going back to the list of questions, it then runs properly.

**Comment by christianp** [comment] 2016-06-06 08:34
This is caused by the server running out of memory, not a bug in Numbas. I'll see if I can fix that, but I'm closing this issue.

**Closed by christianp** 2016-06-06 08:34 UTC
